# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'
use_frameworks!

target 'SocialInnovationChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  # Pods for SocialInnovationChallenge

  target 'SocialInnovationChallengeTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
  end

  target 'SocialInnovationChallengeUITests' do
    # Pods for testing
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
  end

end
